MAINT: increase IP range
stfc/cloud-capi-values pull request #23
Opened 2024-07-08 11:59 UTC by anish-mudaraddi

running into issues where we run out of IPs for large clusters like jupyterhub.

since we provide a fully private network space for k8s we should be fine going to /16

we cap most users at 500 ports so it shouldn't cause issue to enable for everyone

NOTE: This does need to be tested - worth using this branch to spin up JupyterHub next time we need to.

2024-07-18 07:28 UTC, meoflynn requested changes

2024-07-18 07:28 UTC, meoflynn commented on values.yaml
> +    nodeCidr: 192.168.0.0/16
The stackHPC chart had used `192.168.3.0/24` by default originally, should we change this one from `192.168.0.0/16` to `192.168.3.0/16` so we are using the same subnet?

2024-08-21 13:30 UTC, jacob-ward commented on values.yaml
> +    nodeCidr: 192.168.0.0/16
Having done a bit of subnet maths, if we want to keep this subnet in the 192.168 range for visual distinctiveness then my suggestion would be 192.168.128.0/17

2024-09-09 10:03 UTC, RWhiting78 approved these changes

2024-09-09 10:05 UTC, meoflynn approved these changes

2024-09-09 10:05 UTC, merged