ENH: setup dependencies.json
stfc/cloud-capi-values pull request #31
Opened 2024-10-01 13:30 UTC by anish-mudaraddi

having a separate dependencies file makes it easier for us to update versions and potentially use dependabot or something similar for this repo

2024-10-16 10:10 UTC, meoflynn requested changes

2024-10-16 10:10 UTC, meoflynn commented on dependencies.json
> +    "capo-provider-version": "v0.10.4",
Could we update the capo provider version to `v0.11.0` ?

2024-10-16 10:11 UTC, meoflynn commented on dependencies.json
> +    "capo-addon-version": "0.5.9",
Can we also update the capo-addon to 0.7.0?

2024-10-16 10:18 UTC, anish-mudaraddi commented on dependencies.json
> +    "capo-provider-version": "v0.10.4",
cluster api provider openstack - CAPO is v0.10.5 - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.10.5 - i'll update that and the addon-version which should be 0.7.0

if you're referring to azimuth-cloud/capi-helm-charts chart version - users should automatically use the most up-to-date chart when they follow our docs

2024-10-16 10:23 UTC, meoflynn commented on dependencies.json
> +    "capo-addon-version": "0.7.0",
could we change this variable name slightly? e.g `aziumuth-capo-addon`?

2024-10-16 10:26 UTC, meoflynn commented on dependencies.json
> +    "capo-provider-version": "v0.10.4",
Ah I got the variables mixed up with what they refer to 😅

2024-11-06 15:19 UTC, gmatthews20 approved these changes

2024-11-20 11:51 UTC, anish-mudaraddi commented
I edited the latest commit - you didn't change the variable name in the script to match the change in dependency name - needs re-review @meoflynn

2024-11-20 11:57 UTC, meoflynn commented
Good catch, I didn't realize I forgot to update the variable name 😅

2024-11-20 11:58 UTC, meoflynn approved these changes

2024-11-27 10:28 UTC, RJaliliSTFC approved these changes

2024-11-29 09:56 UTC, merged